/**
 * The Java half of the JNI bindings for an Ivy protocol.
 */
public class IvyProtocol {
    static {
        System.loadLibrary("pkg_protocol");
    }

    /* TODO: this should be generated by Ivy or something. */
}
